name: Get data converted to csv

on:
  schedule:
  - cron:  '00 6 * * *' # run every day at 06:00 UTC
  workflow_dispatch: ~

jobs:
  convert_data:
  
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Convert data to CSV
      run: |
        ./run_converter.sh
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Convert json -> xml
        commit_user_name: chnuessli
        commit_user_email: chrigi@chnuessli.ch
        commit_author: GitHub Action Bot <chrigi@chnuessli.ch>